steps:
  - name: "node:16" # Or a suitable Node.js version
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd client
        npm install
        npm run build

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args: [
        "run",
        "deploy",
        "voltsense", # Replace with your service name
        "--region=us-central1", # Replace with your desired region (e.g., us-central1)
        "--source=client", # Path to the Next.js app directory
        "--platform=managed",
        "--allow-unauthenticated", # For initial testing - secure later!
        "--set-env-vars-file=.env",
      ] # Path to your environment variables file

# images:
#   - "gcr.io/$PROJECT_ID/your-service-name" # Replace with your image name

secrets:
  - name: "NEXT_PUBLIC_FIREBASE_API_KEY" # Name of the Cloud Build secret
    secretEnv: "AIzaSyDEKdG3s90CEmlWjoqZRYbXtgw9vGyb1-0" # Environment variable name in Cloud Run
  - name: "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
    secretEnv: "voltsense-9ff7b.firebaseapp.com"
  - name: "NEXT_PUBLIC_FIREBASE_PROJECT_ID"
    secretEnv: "voltsense-9ff7b"
  - name: "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
    secretEnv: "voltsense-9ff7b.firebasestorage.app"
  - name: "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
    secretEnv: "110999938896"
  - name: "NEXT_PUBLIC_FIREBASE_APP_ID"
    secretEnv: "1:110999938896:web:36a1e646efe052458e2e55"
