steps:
  - name: "node:16" # Or a suitable Node.js version
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd client
        npm install
        npm run build

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args: [
        "run",
        "deploy",
        "voltsense", # Replace with your service name
        "--region=us-central1", # Replace with your desired region (e.g., us-central1)
        "--source=client", # Path to the Next.js app directory
        "--platform=managed",
        "--allow-unauthenticated", # For initial testing - secure later!
        "--set-env-vars-file=.env",
      ] # Path to your environment variables file

# images:
#   - "gcr.io/$PROJECT_ID/your-service-name" # Replace with your image name

